name: Setup Webhook

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  setup_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Webhook
        uses: peter-evans/create-pull-request@v3
        with:
          token: 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
          commit-message: "Add webhook"
          branch: "add-webhook"
          title: "Add webhook"
          body: |
            {
              "name": "web",
              "config": {
                "url": "https://api.github.com/repos/msarih/RepoB/dispatches",
                "content_type": "json",
                "insecure_ssl": "0",
              },
              "events": ["pull_request"],
              "active": true
            }
